import { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
  AreaChart, Area, PieChart, Pie, Cell,
} from 'recharts';
import {
  AlertTriangle, Camera, Activity, TrendingUp, TrendingDown,
  FileText, Download, CheckCircle, X,
} from 'lucide-react';
import { alerts, violationsData, weeklyViolationData, classDistributionData, cameras } from '../data/mockData';

/*  CSV / Report helpers  */
function downloadCSV(data, filename) {
  const headers = ['ID', 'Date/Time', 'Camera', 'Type', 'Confidence', 'Zone', 'Severity', 'Worker'];
  const rows = data.map(v => [
    v.id, v.time, v.camera, v.type,
    `${(v.confidence * 100).toFixed(0)}%`,
    v.zone, v.severity, v.worker ?? 'Unknown',
  ]);
  const csv = [headers, ...rows]
    .map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(','))
    .join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadOSHAReport(data) {
  const now = new Date().toLocaleString();
  const rows = data.map(v => `
    <tr>
      <td>${v.id}</td><td>${v.time}</td><td>${v.camera}</td>
      <td>${v.type}</td><td>${(v.confidence*100).toFixed(0)}%</td>
      <td>${v.zone}</td><td>${v.severity.toUpperCase()}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>OSHA 29 CFR 1926 Compliance Report — SafeScan</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; background: #fff; }
    h1   { font-size: 22px; color: #1e3a5f; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
    h2   { font-size: 15px; color: #374151; margin-top: 28px; }
    .meta{ display:flex; gap:40px; background:#f0f7ff; padding:14px 18px; border-radius:8px; margin:20px 0; font-size:13px; }
    .meta div strong { display:block; font-size:11px; color:#6b7280; text-transform:uppercase; }
    table{ width:100%; border-collapse:collapse; margin-top:12px; font-size:13px; }
    th   { background:#1e3a5f; color:#fff; padding:10px 12px; text-align:left; font-size:12px; }
    td   { padding:9px 12px; border-bottom:1px solid #e5e7eb; }
    tr:nth-child(even) td { background:#f9fafb; }
    .badge { padding:2px 8px; border-radius:4px; font-size:11px; font-weight:700; }
    .critical{ background:#fee2e2; color:#dc2626; }
    .high    { background:#fef3c7; color:#d97706; }
    .medium  { background:#dbeafe; color:#2563eb; }
    .footer  { margin-top:40px; font-size:11px; color:#9ca3af; border-top:1px solid #e5e7eb; padding-top:14px; }
    @media print { body { margin:20px; } }
  </style>
</head>
<body>
  <h1> SafeScan — OSHA 29 CFR 1926 Compliance Report</h1>
  <div class="meta">
    <div><strong>Site</strong>Construction Site Alpha</div>
    <div><strong>Report Date</strong>${now}</div>
    <div><strong>Total Violations</strong>${data.length}</div>
    <div><strong>Critical</strong>${data.filter(v=>v.severity==='critical').length}</div>
    <div><strong>Regulation</strong>OSHA 29 CFR 1926.100 / 1926.102</div>
  </div>
  <h2>Violation Log — All PPE Non-Compliance Events</h2>
  <table>
    <thead><tr><th>ID</th><th>Date/Time</th><th>Camera</th><th>Type</th><th>Confidence</th><th>Zone</th><th>Severity</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <h2>Summary</h2>
  <p>No-Helmet violations: <strong>${data.filter(v=>v.type==='No Helmet').length}</strong> &nbsp;|&nbsp;
     No-Vest violations: <strong>${data.filter(v=>v.type==='No Vest').length}</strong> &nbsp;|&nbsp;
     Avg. Confidence: <strong>${(data.reduce((s,v)=>s+v.confidence,0)/data.length*100).toFixed(1)}%</strong></p>
  <h2>Corrective Actions Required</h2>
  <ul>
    <li>All critical violations require immediate corrective action per OSHA 29 CFR 1926.100(a).</li>
    <li>Workers detected without helmets must be removed from the hazard zone immediately.</li>
    <li>Retrain workers found in non-compliance. Document in safety training log.</li>
    <li>Review camera coverage for blind-spot areas with repeated violations.</li>
  </ul>
  <div class="footer">
    Generated by SafeScan · YOLOv8m PPE Detection System · Report Hash: ${Math.random().toString(36).slice(2,10).toUpperCase()}
    · This report is audit-ready for OSHA inspection under 29 CFR 1926 Subpart E.
  </div>
  <script>window.onload=()=>window.print();<\/script>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  window.open(url, '_blank');
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}

/*  Toast notification  */
function Toast({ msg, type, onClose }) {
  return (
    <div style={{
      position: 'fixed', bottom: 28, right: 28, zIndex: 999,
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '13px 18px',
      background: type === 'success' ? 'rgba(16,185,129,0.12)' : 'rgba(239,68,68,0.12)',
      border: `1px solid ${type === 'success' ? 'rgba(16,185,129,0.4)' : 'rgba(239,68,68,0.4)'}`,
      borderRadius: 'var(--radius-md)',
      backdropFilter: 'blur(20px)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
      color: 'var(--text-primary)',
      fontSize: 13, fontWeight: 600,
      animation: 'fade-up 0.3s ease',
      minWidth: 260,
    }}>
      {type === 'success'
        ? <CheckCircle size={16} style={{ color: 'var(--accent-green)', flexShrink: 0 }}/>
        : <AlertTriangle size={16} style={{ color: 'var(--accent-red)', flexShrink: 0 }}/>}
      <span style={{ flex: 1 }}>{msg}</span>
      <button onClick={onClose} style={{ background:'none', border:'none', cursor:'pointer', color:'var(--text-muted)', padding:2 }}>
        <X size={14}/>
      </button>
    </div>
  );
}

/*  Custom tooltip  */
const CustomTooltip = ({ active, payload, label }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="glass-card" style={{ padding: '10px 14px', border: '1px solid var(--color-border)' }}>
      <div style={{ fontSize: 12, fontWeight: 700, marginBottom: 6, color: 'var(--text-muted)' }}>{label}</div>
      {payload.map((p, i) => (
        <div key={i} style={{ fontSize: 13, color: p.color, marginBottom: 2 }}>
          {p.name}: <strong>{p.value}</strong>
        </div>
      ))}
    </div>
  );
};

/*  Dashboard  */
export default function Dashboard() {
  const complianceRate = 82;
  const [toast, setToast] = useState(null);

  const showToast = (msg, type = 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3500);
  };

  const handleExportReport = () => {
    downloadCSV(violationsData, `safesite-report-${new Date().toISOString().slice(0,10)}.csv`);
    showToast(' Report exported as CSV — check your Downloads folder', 'success');
  };

  const stats = [
    { label: 'Active Cameras',   value: '5/6',            change: '-1 offline',        dir: 'neutral', color: 'var(--accent-blue)',  bg: '#3b82f6' },
    { label: 'Violations Today', value: '14',             change: '+3 vs yesterday',   dir: 'up',      color: 'var(--accent-red)',   bg: '#ef4444' },
    { label: 'Workers Detected', value: '234',            change: '+18 since 8am',     dir: 'neutral', color: 'var(--accent-cyan)',  bg: '#06b6d4' },
    { label: 'Compliance Rate',  value: `${complianceRate}%`, change: '-2% from last week', dir: 'up', color: 'var(--accent-amber)', bg: '#f59e0b' },
  ];

  return (
    <div>
      {/* Toast */}
      {toast && <Toast msg={toast.msg} type={toast.type} onClose={() => setToast(null)} />}

      <div className="page-header">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h1 className="page-title">Safety Overview</h1>
            <p className="page-subtitle">Construction Site Alpha · {new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})} · Real-time monitoring</p>
          </div>
          <div style={{ display: 'flex', gap: 10 }}>
            {/*  WORKING: Export Report → downloads CSV */}
            <button className="btn btn-ghost btn-sm" onClick={handleExportReport}>
              <FileText size={14}/> Export Report
            </button>
            {/*  WORKING: Live Feeds → navigates to /live */}
            <Link to="/live" className="btn btn-primary btn-sm">
              <Camera size={14}/> Live Feeds
            </Link>
          </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="stats-grid">
        {stats.map((s, i) => (
          <div key={i} className="glass-card stat-card">
            <div className="stat-card-accent" style={{ background: s.bg }}/>
            <div className="stat-label">{s.label}</div>
            <div className="stat-value" style={{ color: s.color }}>{s.value}</div>
            <div className={`stat-change ${s.dir}`}>
              {s.dir === 'up' ? <TrendingUp size={12}/> : s.dir === 'down' ? <TrendingDown size={12}/> : <Activity size={12}/>}
              {s.change}
            </div>
          </div>
        ))}
      </div>

      <div className="grid-2" style={{ marginBottom: 20 }}>
        {/* Weekly violations bar chart */}
        <div className="glass-card chart-container">
          <div className="chart-header">
            <div>
              <div className="chart-title">Weekly Violations</div>
              <div className="chart-subtitle">Helmet vs Vest violations by day</div>
            </div>
            <span className="badge badge-red">This Week</span>
          </div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={weeklyViolationData} barSize={12} barGap={3}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(56,100,180,0.12)" />
              <XAxis dataKey="day" tick={{ fill: '#4a6080', fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: '#4a6080', fontSize: 12 }} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Legend wrapperStyle={{ fontSize: 12, paddingTop: 10 }} />
              <Bar dataKey="helmet" name="No Helmet" fill="#ef4444" radius={[3,3,0,0]} />
              <Bar dataKey="vest"   name="No Vest"   fill="#f97316" radius={[3,3,0,0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Class distribution pie */}
        <div className="glass-card chart-container">
          <div className="chart-header">
            <div>
              <div className="chart-title">Detection Class Distribution</div>
              <div className="chart-subtitle">Today's inference breakdown</div>
            </div>
            <span className="badge badge-blue">Today</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
            <ResponsiveContainer width={180} height={180}>
              <PieChart>
                <Pie data={classDistributionData} cx="50%" cy="50%" innerRadius={50} outerRadius={80} paddingAngle={3} dataKey="value">
                  {classDistributionData.map((entry, i) => (
                    <Cell key={i} fill={entry.color} stroke="transparent" />
                  ))}
                </Pie>
                <Tooltip content={<CustomTooltip />} />
              </PieChart>
            </ResponsiveContainer>
            <div style={{ flex: 1 }}>
              {classDistributionData.map((d, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                  <div style={{ width: 10, height: 10, borderRadius: 2, background: d.color, flexShrink: 0 }}/>
                  <span style={{ fontSize: 12, color: 'var(--text-secondary)', flex: 1 }}>{d.name}</span>
                  <span style={{ fontSize: 12, fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)' }}>{d.value}%</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Compliance Gauge */}
      <div className="glass-card chart-container" style={{ marginBottom: 20 }}>
        <div className="chart-header">
          <div>
            <div className="chart-title">Compliance Rate — Site Alpha</div>
            <div className="chart-subtitle">Workers wearing both helmet & vest</div>
          </div>
          <div style={{ display: 'flex', gap: 10 }}>
            <span className="badge badge-green badge-dot">Live</span>
            <span className="badge badge-amber">{complianceRate}%</span>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 24, flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 240 }}>
            <div style={{ height: 12, background: 'rgba(255,255,255,0.06)', borderRadius: 100, overflow: 'hidden' }}>
              <div style={{ width: `${complianceRate}%`, height: '100%', background: 'var(--gradient-blue)', borderRadius: 100, transition: 'width 1s ease' }}/>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8, fontSize: 12, color: 'var(--text-muted)' }}>
              <span>0%</span><span>Target: 95%</span><span>100%</span>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 20 }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 28, fontWeight: 900, color: 'var(--accent-green)' }}>192</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Compliant</div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div style={{ fontSize: 28, fontWeight: 900, color: 'var(--accent-red)' }}>42</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Violations</div>
            </div>
          </div>
        </div>
      </div>

      {/* Recent Violations Table */}
      <div className="glass-card" style={{ marginBottom: 20 }}>
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div className="chart-title">Recent Violations</div>
            <div className="chart-subtitle">Latest PPE non-compliance events</div>
          </div>
          <Link to="/violations" className="btn btn-ghost btn-sm">View All →</Link>
        </div>
        <div className="violations-table-wrapper">
          <table className="violations-table">
            <thead>
              <tr>
                <th>ID</th><th>Time</th><th>Camera</th><th>Type</th>
                <th>Confidence</th><th>Zone</th><th>Severity</th>
              </tr>
            </thead>
            <tbody>
              {violationsData.slice(0, 6).map(v => (
                <tr key={v.id}>
                  <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--accent-blue)' }}>{v.id}</td>
                  <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12, whiteSpace: 'nowrap' }}>{v.time.split(' ')[1]}</td>
                  <td style={{ fontSize: 13 }}>{v.camera}</td>
                  <td><span className={`badge ${v.type.startsWith('No') ? 'badge-red' : 'badge-blue'}`}>{v.type}</span></td>
                  <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{(v.confidence * 100).toFixed(0)}%</td>
                  <td style={{ fontSize: 12, color: 'var(--text-muted)' }}>{v.zone}</td>
                  <td>
                    <span className={`badge ${v.severity === 'critical' ? 'badge-red' : v.severity === 'high' ? 'badge-amber' : 'badge-blue'}`}>
                      {v.severity}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Camera Status */}
      <div className="glass-card">
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div className="chart-title">Camera Status</div>
          <Link to="/live" className="btn btn-ghost btn-sm"><Camera size={14}/> Manage Cameras</Link>
        </div>
        <div style={{ padding: 20, display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 12 }}>
          {cameras.map(c => (
            <div key={c.id} className="glass-card" style={{ padding: 14 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
                <div style={{ fontSize: 13, fontWeight: 600 }}>{c.name}</div>
                <span className={`badge ${c.status === 'online' ? 'badge-green badge-dot' : 'badge-red'}`}>{c.status}</span>
              </div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>{c.zone}</div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                {c.status === 'online' ? `${c.fps} FPS · ` : 'Offline · '}
                <span style={{ color: c.violations_today > 0 ? 'var(--accent-red)' : 'var(--accent-green)' }}>
                  {c.violations_today} violations
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
